#version 330

layout(std140) uniform DynamicTransforms {
    mat4 ModelViewMat;
    vec4 ColorModulator;
    vec3 ModelOffset;
    mat4 TextureMat;
};

uniform sampler2D Sampler0;

in vec2 texCoord0;
in vec4 vertexColor;

out vec4 fragColor;

// Same as core/msdf_icon but for icons baked with a 6 texel distance range
// instead of 12. The constant must match the -pxrange the atlas was generated
// with: assuming a wider range than the texture holds is what makes small icons
// look washed out, because the antialiasing ramp is then stretched twice as far
// as the real edge. Icons using this shader are generated by gen-icons.ps1.
const float DISTANCE_RANGE = 6.0;

// The edge is pushed out this much of the distance range, which thickens every
// stroke by about a tenth of a pixel at HUD sizes. These icons are line art set
// beside a medium-cut font, and without it they read a weight lighter than the
// text they label. It is deliberately small: tightening the antialiasing on top
// of it, which is what this shader used to do, turns the curves into stairs and
// closes up the globe's grid and the chip's pins.
const float EDGE_BIAS = 0.08;

float median(float r, float g, float b) {
    return max(min(r, g), min(max(r, g), b));
}

void main() {
    vec3 sampleColor = texture(Sampler0, texCoord0).rgb;
    float signedDistance = median(sampleColor.r, sampleColor.g, sampleColor.b) - 0.5 + EDGE_BIAS;
    vec2 derivative = vec2(dFdx(texCoord0.x), dFdy(texCoord0.y)) * textureSize(Sampler0, 0);
    float screenRange = max(DISTANCE_RANGE * inversesqrt(max(dot(derivative, derivative), 0.0001)), 1.0);
    // The reference msdf resolve: the distance in screen pixels, resolved over
    // exactly one of them. Nothing here is tuned to a particular icon size.
    float alpha = clamp(signedDistance * screenRange + 0.5, 0.0, 1.0);

    if (alpha <= 0.001) discard;
    fragColor = vec4(vertexColor.rgb, vertexColor.a * alpha) * ColorModulator;
}
